version: '3'

services:
  mongodb:
    image: mongo
    container_name: core-emotion_mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: "no"
  rmq:
    image: rabbitmq:3.8-management
    container_name: core-emotion_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    restart: "no"
  redis:
    container_name: core-emotion_redis
    image: redis:latest
    restart: "no"
    ports:
      - 6379:6379
